---
language: python
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libpulse-dev swig -y
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install textract
script:
  - ls -lR
  - python generate_resume_template.py
  - python check_wordfile.py
